This task examines variable encoding, repeatedly displaying images with varying degrees of
degredation to encourage participants to sample different areas of the images. The idea is that
less available information will lead to better discrimination memory.

Consisting of an encoding phase and a test phase, images are presented at various levels of 
degredation.

In the encoding phase, participants complete five blocks of an incidental encoding task.
In the first block participants are shown a set of 100 images undegraded and are asked to
answer a binary question about them.
This repeats for four additional blocks with the same set of images being displayed, however, 
some of the images have been degraded to varying degrees.

In the test phase, the another set of 100 images are shown again. This set contains
50 of the images seen during encoding. The reamining 50 images consist of similar lure
images of the remaning 50 images. Participants are asked to deteremine if the displayed
image is identical or similar to an image they had seen during encoding.

Degraded images and condition lists are generated by an external script
Sample condition lists in folder
#--------------------------------------------------------------
#* This was built in SR research experiment builder. I'm not sure what syntax it uses under the hood
#  Conditions and files are read from a data source file
#Encoding phase

Load data source file
iteration_count <- 100
nblock <- 5

While space is not pressed
  Display weclome screen "welcome"
  Check for participant response

Initiate eyetracking set up

While space is not pressed
  Display instructions image
  Check for keyboard response

for i in nblock
  
  Randomly select a decision question without replacement
  while space is not pressed
    Display decision question
    Check for keyboard response
  
  for i in 1:iteration_count
    
    Initiate eyetracking sequence
    for two seconds
      Display trial image as indicated by the condition list
      Check for keyboard response
    Record participant response
    Initiate fixation period
    Initiate Drift Correct

Conclude encoding phase

while space is not pressed
  Display "End of Phase one"
  Check for keyboard response

# Test Phase
while space is not pressed
  Display test phase instructions
  Check for keyboard response

for i in iteration_count
  
  Display trial image as indicated by the condition list
  Check for keyboard response
  Record participant response
  Deteremine accuracy (compare response to valid response in data source)
  Calulate Rt (time of start of trial - time of first resposne)
  Return response, accuracy, and rt (write to output file)
  Initiate fixation period
  Initiate drift correct 

    
Condlude experiment

Write to output file
Print "End of Experiment, Thank you for participating"