This task examines variable encoding, repeatedly displaying images with varying degrees of
degredation to encourage participants to sample different areas of the images. The idea is that
less available information will lead to better discrimination memory.

Consisting of an encoding phase and a test phase, images are presented at various levels of 
degredation.

In the encoding phase, participants complete five blocks of an incidental encoding task.
In the first block participants are shown a set of 100 images undegraded and are asked to
answer a binary question about them.
This repeats for four additional blocks with the same set of images being displayed, however, 
some of the images have been degraded to varying degrees.

In the test phase, the another set of 100 images are shown again. This set contains
50 of the images seen during encoding. The reamining 50 images consist of similar lure
images of the remaning 50 images. Participants are asked to deteremine if the displayed
image is identical or similar to an image they had seen during encoding.

Degraded images and condition lists are generated by an external script
Sample condition lists in folder
#--------------------------------------------------------------
#Encoding phase

print weclome screen "welcome"

Initiate eyetracking set up

Display instructions image

for five iterations
  
  Randomly select a decision question without replacement
  Display decision question
  
  for the length of the condition list (100 trials)
    
    initiate eyetracking sequence
    Display trial image as indicated by the condition list
    Record participant response
    Initiate fixation period
    Initiate Drift Correct

Conclude encoding phase

print "End of Phase one"

# Test Phase
Display test phase instructions

for the length of the condition list
  
  Display trial image as indicated by the condition list
  Record participant response
  Deteremine accuracy
  Calulate Rt
  Return response, accuracy, and rt
  Initiate fixation period
  Initiate drift correct 
  
Condlude experiment

Print "End of Experiment, Thank you for participating"